spring:
  datasource:
    url: jdbc:mysql://localhost:3306/together
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  jwt:
    secretKey: L2YQ3xcDPXCFunobNxiVC9HEbv7P0h7HAap2oLdyLqygtbPWAvw29YJ0TvVubFp
