spring:
  #h2:
  #console:
  #enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
  #path: /h2-console  # H2 Console의 Path
  datasource:
    #driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
    #url: jdbc:h2:mem:testdb  # H2 접속 정보
    #username: sa
    #password:
    url: jdbc:mysql://127.0.0.1:3306/TOgether
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect #org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  jwt:
    secretKey: L2YQ3xcDPXCFunobNxiVC9HEbv7P0h7HAap2oLdyLqygtbPWAvw29YJ0TvVubFp